apiVersion: operator.openshift.io/v1
kind: ServiceCatalogControllerManager
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  generation: 1
  name: cluster
  selfLink: /apis/operator.openshift.io/v1/servicecatalogcontrollermanagers/cluster
spec:
  logLevel: Normal
  managementState: Managed